/******************************************************************
 * Version      Date        Name        Description
 * ****************************************************************
 * V1.0    04-10-2021     Calculator    this is calculator class
 ******************************************************************/
public with sharing class Calculator {
    public Calculator() {

    }

    public Integer sub(Integer a, Integer b){
        return a - b;
    }
}
