/******************************************************************
 * Version      Date        Name        Description
 * ****************************************************************
 * V1.0       
 ******************************************************************/
public with sharing class Calculator {
    public Calculator() {

    }

    public Integer add(Integer a, Integer b){
        return a*b;
    }
}
