/******************************************************************
 * Version      Date        Name        Description
 * ****************************************************************
 * V1.0    04-10-2021     Calculator    this is calculator class, updated comments
 ******************************************************************/
public with sharing class Calculator {
    public Calculator() {
    }
    public Integer add(Integer a, Integer b){
        return a+b;
    }
}
